### ISSUE TITLE
long-reach 0.0.8 do not work with 0.15.31!?

### ISSUE THREAD

**Issue by mEDI-S** [jaguilar/long-reach#13]
Hi,

today get i a forced upgrade to 0.15.31 from 0.15.30 "0.15.30 is no longer avalibele" and long-reach do not work ;( hope it is fixable

rages

mEDI

**Comment by mEDI-S** [comment]
ah ok, i found the controll.lua and used the woraround, now work it again ;) sorry for the wrong issue
thx for the mod

hf

**Comment by cjburkey01** [comment]
How exactly did you fix this?

**Comment by mEDI-S** [comment]
go in running game in config->mods to the long-reach part and change the values and confirm this reactivate the mod

**Comment by cjburkey01** [comment]
I had tried that, but that didn't work. I'm current using a different mod: FactoReach

**Comment by jaguilar** [comment]
Hey all, I'm not maintaining this mod any more, but it sounds like there are others that are fitting the niche. I'll update the readme with a link to them.
