### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Phuizour** [jaguilar/long-reach#5]
Hey.
Well i have tried re-downloading and re-install this mod however for some reason it just doesn't want to work. It says it's enabled on the mods menu however when i load into the game it doesn't work. Got any idea or tips?

**Comment by jaguilar** [comment]
I need more information.

- What Factorio version are you running?
- Did you get it from Steam or direct?
- What version of the mod do you have installed?
- What other mods are you using?

**Comment by Halmex** [comment]
@Phuizour  **IF** you use ShinyBob try this: 
Enable long reach mods by setting "reach_mod = false" in config.lua in the ShinyBob.zip
