### ISSUE TITLE
Bump version to Factorio latest?

### ISSUE THREAD

**Issue by malk0lm** [jaguilar/long-reach#6]
I'd love to have this mod updated again! :)

**Comment by jaguilar** [comment]
I'll leave this open until I can test and make a release tonight. Expect it around 7-8PM ET.

**Comment by paravar** [comment]
Eagerly waiting dude! I can't play w/o this. Thanks.

**Comment by jaguilar** [comment]
Fixed as of 0.0.7.

**Comment by paravar** [comment]
Why the mod is not updated on the official mod server? I mean when I want to instal mod from the MOD menu in the game, it's still outdated. Thanks.

**Comment by jaguilar** [comment]
For some reason, I had forgotten you have to manually upload the zip file to mods.factorio.com. I thought they scanned the github releases. Anyway, that's done now. Please try again and let me know if it is still not working.

**Comment by paravar** [comment]
All good. Thanks again.
