### ISSUE TITLE
can place items anywhere on new map view.

### ISSUE THREAD

**Issue by toric55** [jaguilar/long-reach#8]
current version has unlimited reatch, meaning you can place things anywhere if you haver radar covrage of the location.

**Comment by jaguilar** [comment]
Well, technically, within about ten thousand locations of where you are. Please feel free to adjust the values to suit your tastes. I suspect that around 200 units will give you the full default viewport.

That said, I'm not going to change the behavior of the mod.

**Comment by jaguilar** [comment]
(Good find though! I might not have even thought to try that!)

**Comment by jaguilar** [comment]
On further consideration . . . maybe we should tweak the default values down. I'd like it if someone would measure a reasonable number of units out and send a pull request to update the values. I'm busy . . . playing 0.15. But I'll get around to it eventually if no one else does.

**Comment by utoxin** [comment]
Change request #10 is my suggestion, with rationale in the comments

**Comment by jaguilar** [comment]
Closed by #11.
