### ISSUE TITLE
Adopt the new configuration API

### ISSUE THREAD

**Issue by jaguilar** [jaguilar/long-reach#9]
Perhaps we could provide checkboxes that allow just placing objects in the zoomed out viewport, or anywhere. I want to leave anywhere as the default.

That said, work is quite busy and I'm not feeling enthusiastic about doing this myself. Please comment if you want to take this on and I will provide a code review and merge in a timely fashion.

**Comment by utoxin** [comment]
I like this idea... and I've been getting the itch to maybe try modding Factorio. I can't promise anything, but I may take a crack at it. :)

**Comment by utoxin** [comment]
Some research done over lunch at work, and I can definitely take this on. :) May even have a working implementation tonight.

**Comment by jaguilar** [comment]
Closed by #11.
